version: '3.8'

volumes:
  db-init:
  db-data:

services:
  db:
    build:
      context: ./
      dockerfile: ./docker_files/mysql/Dockerfile
    container_name: twitter-api-sample-db
    restart: on-failure:5
    ports:
      - '3752:3306'
    environment:
      # 今回は勉強用のためセキュリティ無視で直書き
      MYSQL_ROOT_PASSWORD: 'root'
    tty: true
    volumes:
      - db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    networks:
      - twitter_api_sample_net
  backend:
    build:
      context: ./
      dockerfile: ./docker_files/go/Dockerfile
    container_name: twitter-api-sample
    volumes:
      - '.:/go/app'
    ports:
      - '8555:8555'
    tty: true
    stdin_open: true
    environment:
      SIGNINGKEY: ${SIGNINGKEY}
      CREDENTIAL_TOKEN: ${CREDENTIAL_TOKEN}
      CREDENTIAL_SECRET: ${CREDENTIAL_SECRET}
      CALLBACK_URL: ${CALLBACK_URL}
    networks:
      - twitter_api_sample_net
networks:
  default:
    external:
      name: bridge
  twitter_api_sample_net:
    name: docker.internal